FROM node:0.12

RUN mkdir /src

WORKDIR /src
ADD viewserializer/package.json /src/package.json
RUN npm install

ADD viewserializer/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

ADD ./populate_env.sh /populate_env.sh
RUN chmod 755 /populate_env.sh

CMD ["/entrypoint.sh"]
