FROM node:0.12

RUN mkdir /src

WORKDIR /src
ADD assetsserver/package.json /src/package.json
RUN npm install

ADD assetsserver/entrypoint.sh /entrypoint.sh
RUN chmod 755 /entrypoint.sh

ADD ./populate_env.sh /populate_env.sh
RUN chmod 755 /populate_env.sh

EXPOSE 3000

CMD ["/entrypoint.sh"]
